// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zp_meta.proto

#ifndef PROTOBUF_zp_5fmeta_2eproto__INCLUDED
#define PROTOBUF_zp_5fmeta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ZPMeta {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_zp_5fmeta_2eproto();
void protobuf_AssignDesc_zp_5fmeta_2eproto();
void protobuf_ShutdownFile_zp_5fmeta_2eproto();

class Node;
class Partitions;
class MetaCmd;
class MetaCmd_Join;
class MetaCmd_Ping;
class MetaCmd_Update;
class MetaCmd_Sync;
class MetaCmdResponse;
class MetaCmdResponse_Status;

enum MetaCmd_Type {
  MetaCmd_Type_JOIN = 1,
  MetaCmd_Type_PING = 2,
  MetaCmd_Type_UPDATE = 3,
  MetaCmd_Type_SYNC = 4
};
bool MetaCmd_Type_IsValid(int value);
const MetaCmd_Type MetaCmd_Type_Type_MIN = MetaCmd_Type_JOIN;
const MetaCmd_Type MetaCmd_Type_Type_MAX = MetaCmd_Type_SYNC;
const int MetaCmd_Type_Type_ARRAYSIZE = MetaCmd_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* MetaCmd_Type_descriptor();
inline const ::std::string& MetaCmd_Type_Name(MetaCmd_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    MetaCmd_Type_descriptor(), value);
}
inline bool MetaCmd_Type_Parse(
    const ::std::string& name, MetaCmd_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MetaCmd_Type>(
    MetaCmd_Type_descriptor(), name, value);
}
enum MetaCmdResponse_Type {
  MetaCmdResponse_Type_JOIN = 1,
  MetaCmdResponse_Type_PING = 2,
  MetaCmdResponse_Type_UPDATE = 3,
  MetaCmdResponse_Type_SYNC = 4
};
bool MetaCmdResponse_Type_IsValid(int value);
const MetaCmdResponse_Type MetaCmdResponse_Type_Type_MIN = MetaCmdResponse_Type_JOIN;
const MetaCmdResponse_Type MetaCmdResponse_Type_Type_MAX = MetaCmdResponse_Type_SYNC;
const int MetaCmdResponse_Type_Type_ARRAYSIZE = MetaCmdResponse_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* MetaCmdResponse_Type_descriptor();
inline const ::std::string& MetaCmdResponse_Type_Name(MetaCmdResponse_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    MetaCmdResponse_Type_descriptor(), value);
}
inline bool MetaCmdResponse_Type_Parse(
    const ::std::string& name, MetaCmdResponse_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MetaCmdResponse_Type>(
    MetaCmdResponse_Type_descriptor(), name, value);
}
// ===================================================================

class Node : public ::google::protobuf::Message {
 public:
  Node();
  virtual ~Node();
  
  Node(const Node& from);
  
  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();
  
  void Swap(Node* other);
  
  // implements Message ----------------------------------------------
  
  Node* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes ip = 1;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 1;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const void* value, size_t size);
  inline ::std::string* mutable_ip();
  
  // required int32 port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:ZPMeta.Node)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* ip_;
  static const ::std::string _default_ip_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// -------------------------------------------------------------------

class Partitions : public ::google::protobuf::Message {
 public:
  Partitions();
  virtual ~Partitions();
  
  Partitions(const Partitions& from);
  
  inline Partitions& operator=(const Partitions& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Partitions& default_instance();
  
  void Swap(Partitions* other);
  
  // implements Message ----------------------------------------------
  
  Partitions* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Partitions& from);
  void MergeFrom(const Partitions& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required .ZPMeta.Node master = 2;
  inline bool has_master() const;
  inline void clear_master();
  static const int kMasterFieldNumber = 2;
  inline const ::ZPMeta::Node& master() const;
  inline ::ZPMeta::Node* mutable_master();
  
  // repeated .ZPMeta.Node slaves = 3;
  inline int slaves_size() const;
  inline void clear_slaves();
  static const int kSlavesFieldNumber = 3;
  inline const ::ZPMeta::Node& slaves(int index) const;
  inline ::ZPMeta::Node* mutable_slaves(int index);
  inline ::ZPMeta::Node* add_slaves();
  inline const ::google::protobuf::RepeatedPtrField< ::ZPMeta::Node >&
      slaves() const;
  inline ::google::protobuf::RepeatedPtrField< ::ZPMeta::Node >*
      mutable_slaves();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.Partitions)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::ZPMeta::Node* master_;
  ::google::protobuf::RepeatedPtrField< ::ZPMeta::Node > slaves_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Partitions* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmd_Join : public ::google::protobuf::Message {
 public:
  MetaCmd_Join();
  virtual ~MetaCmd_Join();
  
  MetaCmd_Join(const MetaCmd_Join& from);
  
  inline MetaCmd_Join& operator=(const MetaCmd_Join& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmd_Join& default_instance();
  
  void Swap(MetaCmd_Join* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmd_Join* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmd_Join& from);
  void MergeFrom(const MetaCmd_Join& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .ZPMeta.Node node = 1;
  inline bool has_node() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 1;
  inline const ::ZPMeta::Node& node() const;
  inline ::ZPMeta::Node* mutable_node();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmd.Join)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::ZPMeta::Node* node_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmd_Join* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmd_Ping : public ::google::protobuf::Message {
 public:
  MetaCmd_Ping();
  virtual ~MetaCmd_Ping();
  
  MetaCmd_Ping(const MetaCmd_Ping& from);
  
  inline MetaCmd_Ping& operator=(const MetaCmd_Ping& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmd_Ping& default_instance();
  
  void Swap(MetaCmd_Ping* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmd_Ping* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmd_Ping& from);
  void MergeFrom(const MetaCmd_Ping& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .ZPMeta.Node node = 1;
  inline bool has_node() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 1;
  inline const ::ZPMeta::Node& node() const;
  inline ::ZPMeta::Node* mutable_node();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmd.Ping)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::ZPMeta::Node* node_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmd_Ping* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmd_Update : public ::google::protobuf::Message {
 public:
  MetaCmd_Update();
  virtual ~MetaCmd_Update();
  
  MetaCmd_Update(const MetaCmd_Update& from);
  
  inline MetaCmd_Update& operator=(const MetaCmd_Update& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmd_Update& default_instance();
  
  void Swap(MetaCmd_Update* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmd_Update* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmd_Update& from);
  void MergeFrom(const MetaCmd_Update& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ZPMeta.Partitions info = 1;
  inline int info_size() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 1;
  inline const ::ZPMeta::Partitions& info(int index) const;
  inline ::ZPMeta::Partitions* mutable_info(int index);
  inline ::ZPMeta::Partitions* add_info();
  inline const ::google::protobuf::RepeatedPtrField< ::ZPMeta::Partitions >&
      info() const;
  inline ::google::protobuf::RepeatedPtrField< ::ZPMeta::Partitions >*
      mutable_info();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmd.Update)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::ZPMeta::Partitions > info_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmd_Update* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmd_Sync : public ::google::protobuf::Message {
 public:
  MetaCmd_Sync();
  virtual ~MetaCmd_Sync();
  
  MetaCmd_Sync(const MetaCmd_Sync& from);
  
  inline MetaCmd_Sync& operator=(const MetaCmd_Sync& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmd_Sync& default_instance();
  
  void Swap(MetaCmd_Sync* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmd_Sync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmd_Sync& from);
  void MergeFrom(const MetaCmd_Sync& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .ZPMeta.Node node = 1;
  inline bool has_node() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 1;
  inline const ::ZPMeta::Node& node() const;
  inline ::ZPMeta::Node* mutable_node();
  
  // required int32 filenum = 2 [default = 0];
  inline bool has_filenum() const;
  inline void clear_filenum();
  static const int kFilenumFieldNumber = 2;
  inline ::google::protobuf::int32 filenum() const;
  inline void set_filenum(::google::protobuf::int32 value);
  
  // required int32 offset = 3 [default = 0];
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 3;
  inline ::google::protobuf::int32 offset() const;
  inline void set_offset(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmd.Sync)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::ZPMeta::Node* node_;
  ::google::protobuf::int32 filenum_;
  ::google::protobuf::int32 offset_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmd_Sync* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmd : public ::google::protobuf::Message {
 public:
  MetaCmd();
  virtual ~MetaCmd();
  
  MetaCmd(const MetaCmd& from);
  
  inline MetaCmd& operator=(const MetaCmd& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmd& default_instance();
  
  void Swap(MetaCmd* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmd& from);
  void MergeFrom(const MetaCmd& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef MetaCmd_Join Join;
  typedef MetaCmd_Ping Ping;
  typedef MetaCmd_Update Update;
  typedef MetaCmd_Sync Sync;
  
  typedef MetaCmd_Type Type;
  static const Type JOIN = MetaCmd_Type_JOIN;
  static const Type PING = MetaCmd_Type_PING;
  static const Type UPDATE = MetaCmd_Type_UPDATE;
  static const Type SYNC = MetaCmd_Type_SYNC;
  static inline bool Type_IsValid(int value) {
    return MetaCmd_Type_IsValid(value);
  }
  static const Type Type_MIN =
    MetaCmd_Type_Type_MIN;
  static const Type Type_MAX =
    MetaCmd_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    MetaCmd_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return MetaCmd_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return MetaCmd_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return MetaCmd_Type_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .ZPMeta.MetaCmd.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::ZPMeta::MetaCmd_Type type() const;
  inline void set_type(::ZPMeta::MetaCmd_Type value);
  
  // optional .ZPMeta.MetaCmd.Join join = 2;
  inline bool has_join() const;
  inline void clear_join();
  static const int kJoinFieldNumber = 2;
  inline const ::ZPMeta::MetaCmd_Join& join() const;
  inline ::ZPMeta::MetaCmd_Join* mutable_join();
  
  // optional .ZPMeta.MetaCmd.Ping ping = 3;
  inline bool has_ping() const;
  inline void clear_ping();
  static const int kPingFieldNumber = 3;
  inline const ::ZPMeta::MetaCmd_Ping& ping() const;
  inline ::ZPMeta::MetaCmd_Ping* mutable_ping();
  
  // optional .ZPMeta.MetaCmd.Update update = 4;
  inline bool has_update() const;
  inline void clear_update();
  static const int kUpdateFieldNumber = 4;
  inline const ::ZPMeta::MetaCmd_Update& update() const;
  inline ::ZPMeta::MetaCmd_Update* mutable_update();
  
  // optional .ZPMeta.MetaCmd.Sync sync = 5;
  inline bool has_sync() const;
  inline void clear_sync();
  static const int kSyncFieldNumber = 5;
  inline const ::ZPMeta::MetaCmd_Sync& sync() const;
  inline ::ZPMeta::MetaCmd_Sync* mutable_sync();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmd)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  int type_;
  ::ZPMeta::MetaCmd_Join* join_;
  ::ZPMeta::MetaCmd_Ping* ping_;
  ::ZPMeta::MetaCmd_Update* update_;
  ::ZPMeta::MetaCmd_Sync* sync_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmd* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmdResponse_Status : public ::google::protobuf::Message {
 public:
  MetaCmdResponse_Status();
  virtual ~MetaCmdResponse_Status();
  
  MetaCmdResponse_Status(const MetaCmdResponse_Status& from);
  
  inline MetaCmdResponse_Status& operator=(const MetaCmdResponse_Status& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmdResponse_Status& default_instance();
  
  void Swap(MetaCmdResponse_Status* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmdResponse_Status* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmdResponse_Status& from);
  void MergeFrom(const MetaCmdResponse_Status& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);
  
  // optional bytes msg = 2;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 2;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const void* value, size_t size);
  inline ::std::string* mutable_msg();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmdResponse.Status)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 code_;
  ::std::string* msg_;
  static const ::std::string _default_msg_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmdResponse_Status* default_instance_;
};
// -------------------------------------------------------------------

class MetaCmdResponse : public ::google::protobuf::Message {
 public:
  MetaCmdResponse();
  virtual ~MetaCmdResponse();
  
  MetaCmdResponse(const MetaCmdResponse& from);
  
  inline MetaCmdResponse& operator=(const MetaCmdResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaCmdResponse& default_instance();
  
  void Swap(MetaCmdResponse* other);
  
  // implements Message ----------------------------------------------
  
  MetaCmdResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaCmdResponse& from);
  void MergeFrom(const MetaCmdResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef MetaCmdResponse_Status Status;
  
  typedef MetaCmdResponse_Type Type;
  static const Type JOIN = MetaCmdResponse_Type_JOIN;
  static const Type PING = MetaCmdResponse_Type_PING;
  static const Type UPDATE = MetaCmdResponse_Type_UPDATE;
  static const Type SYNC = MetaCmdResponse_Type_SYNC;
  static inline bool Type_IsValid(int value) {
    return MetaCmdResponse_Type_IsValid(value);
  }
  static const Type Type_MIN =
    MetaCmdResponse_Type_Type_MIN;
  static const Type Type_MAX =
    MetaCmdResponse_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    MetaCmdResponse_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return MetaCmdResponse_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return MetaCmdResponse_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return MetaCmdResponse_Type_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .ZPMeta.MetaCmdResponse.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::ZPMeta::MetaCmdResponse_Type type() const;
  inline void set_type(::ZPMeta::MetaCmdResponse_Type value);
  
  // required .ZPMeta.MetaCmdResponse.Status status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline const ::ZPMeta::MetaCmdResponse_Status& status() const;
  inline ::ZPMeta::MetaCmdResponse_Status* mutable_status();
  
  // @@protoc_insertion_point(class_scope:ZPMeta.MetaCmdResponse)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  int type_;
  ::ZPMeta::MetaCmdResponse_Status* status_;
  friend void  protobuf_AddDesc_zp_5fmeta_2eproto();
  friend void protobuf_AssignDesc_zp_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_zp_5fmeta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MetaCmdResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// Node

// required bytes ip = 1;
inline bool Node::has_ip() const {
  return _has_bit(0);
}
inline void Node::clear_ip() {
  if (ip_ != &_default_ip_) {
    ip_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Node::ip() const {
  return *ip_;
}
inline void Node::set_ip(const ::std::string& value) {
  _set_bit(0);
  if (ip_ == &_default_ip_) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void Node::set_ip(const char* value) {
  _set_bit(0);
  if (ip_ == &_default_ip_) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void Node::set_ip(const void* value, size_t size) {
  _set_bit(0);
  if (ip_ == &_default_ip_) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Node::mutable_ip() {
  _set_bit(0);
  if (ip_ == &_default_ip_) {
    ip_ = new ::std::string;
  }
  return ip_;
}

// required int32 port = 2;
inline bool Node::has_port() const {
  return _has_bit(1);
}
inline void Node::clear_port() {
  port_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Node::port() const {
  return port_;
}
inline void Node::set_port(::google::protobuf::int32 value) {
  _set_bit(1);
  port_ = value;
}

// -------------------------------------------------------------------

// Partitions

// required int32 id = 1;
inline bool Partitions::has_id() const {
  return _has_bit(0);
}
inline void Partitions::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Partitions::id() const {
  return id_;
}
inline void Partitions::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required .ZPMeta.Node master = 2;
inline bool Partitions::has_master() const {
  return _has_bit(1);
}
inline void Partitions::clear_master() {
  if (master_ != NULL) master_->::ZPMeta::Node::Clear();
  _clear_bit(1);
}
inline const ::ZPMeta::Node& Partitions::master() const {
  return master_ != NULL ? *master_ : *default_instance_->master_;
}
inline ::ZPMeta::Node* Partitions::mutable_master() {
  _set_bit(1);
  if (master_ == NULL) master_ = new ::ZPMeta::Node;
  return master_;
}

// repeated .ZPMeta.Node slaves = 3;
inline int Partitions::slaves_size() const {
  return slaves_.size();
}
inline void Partitions::clear_slaves() {
  slaves_.Clear();
}
inline const ::ZPMeta::Node& Partitions::slaves(int index) const {
  return slaves_.Get(index);
}
inline ::ZPMeta::Node* Partitions::mutable_slaves(int index) {
  return slaves_.Mutable(index);
}
inline ::ZPMeta::Node* Partitions::add_slaves() {
  return slaves_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ZPMeta::Node >&
Partitions::slaves() const {
  return slaves_;
}
inline ::google::protobuf::RepeatedPtrField< ::ZPMeta::Node >*
Partitions::mutable_slaves() {
  return &slaves_;
}

// -------------------------------------------------------------------

// MetaCmd_Join

// required .ZPMeta.Node node = 1;
inline bool MetaCmd_Join::has_node() const {
  return _has_bit(0);
}
inline void MetaCmd_Join::clear_node() {
  if (node_ != NULL) node_->::ZPMeta::Node::Clear();
  _clear_bit(0);
}
inline const ::ZPMeta::Node& MetaCmd_Join::node() const {
  return node_ != NULL ? *node_ : *default_instance_->node_;
}
inline ::ZPMeta::Node* MetaCmd_Join::mutable_node() {
  _set_bit(0);
  if (node_ == NULL) node_ = new ::ZPMeta::Node;
  return node_;
}

// -------------------------------------------------------------------

// MetaCmd_Ping

// required .ZPMeta.Node node = 1;
inline bool MetaCmd_Ping::has_node() const {
  return _has_bit(0);
}
inline void MetaCmd_Ping::clear_node() {
  if (node_ != NULL) node_->::ZPMeta::Node::Clear();
  _clear_bit(0);
}
inline const ::ZPMeta::Node& MetaCmd_Ping::node() const {
  return node_ != NULL ? *node_ : *default_instance_->node_;
}
inline ::ZPMeta::Node* MetaCmd_Ping::mutable_node() {
  _set_bit(0);
  if (node_ == NULL) node_ = new ::ZPMeta::Node;
  return node_;
}

// -------------------------------------------------------------------

// MetaCmd_Update

// repeated .ZPMeta.Partitions info = 1;
inline int MetaCmd_Update::info_size() const {
  return info_.size();
}
inline void MetaCmd_Update::clear_info() {
  info_.Clear();
}
inline const ::ZPMeta::Partitions& MetaCmd_Update::info(int index) const {
  return info_.Get(index);
}
inline ::ZPMeta::Partitions* MetaCmd_Update::mutable_info(int index) {
  return info_.Mutable(index);
}
inline ::ZPMeta::Partitions* MetaCmd_Update::add_info() {
  return info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ZPMeta::Partitions >&
MetaCmd_Update::info() const {
  return info_;
}
inline ::google::protobuf::RepeatedPtrField< ::ZPMeta::Partitions >*
MetaCmd_Update::mutable_info() {
  return &info_;
}

// -------------------------------------------------------------------

// MetaCmd_Sync

// required .ZPMeta.Node node = 1;
inline bool MetaCmd_Sync::has_node() const {
  return _has_bit(0);
}
inline void MetaCmd_Sync::clear_node() {
  if (node_ != NULL) node_->::ZPMeta::Node::Clear();
  _clear_bit(0);
}
inline const ::ZPMeta::Node& MetaCmd_Sync::node() const {
  return node_ != NULL ? *node_ : *default_instance_->node_;
}
inline ::ZPMeta::Node* MetaCmd_Sync::mutable_node() {
  _set_bit(0);
  if (node_ == NULL) node_ = new ::ZPMeta::Node;
  return node_;
}

// required int32 filenum = 2 [default = 0];
inline bool MetaCmd_Sync::has_filenum() const {
  return _has_bit(1);
}
inline void MetaCmd_Sync::clear_filenum() {
  filenum_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 MetaCmd_Sync::filenum() const {
  return filenum_;
}
inline void MetaCmd_Sync::set_filenum(::google::protobuf::int32 value) {
  _set_bit(1);
  filenum_ = value;
}

// required int32 offset = 3 [default = 0];
inline bool MetaCmd_Sync::has_offset() const {
  return _has_bit(2);
}
inline void MetaCmd_Sync::clear_offset() {
  offset_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 MetaCmd_Sync::offset() const {
  return offset_;
}
inline void MetaCmd_Sync::set_offset(::google::protobuf::int32 value) {
  _set_bit(2);
  offset_ = value;
}

// -------------------------------------------------------------------

// MetaCmd

// required .ZPMeta.MetaCmd.Type type = 1;
inline bool MetaCmd::has_type() const {
  return _has_bit(0);
}
inline void MetaCmd::clear_type() {
  type_ = 1;
  _clear_bit(0);
}
inline ::ZPMeta::MetaCmd_Type MetaCmd::type() const {
  return static_cast< ::ZPMeta::MetaCmd_Type >(type_);
}
inline void MetaCmd::set_type(::ZPMeta::MetaCmd_Type value) {
  GOOGLE_DCHECK(::ZPMeta::MetaCmd_Type_IsValid(value));
  _set_bit(0);
  type_ = value;
}

// optional .ZPMeta.MetaCmd.Join join = 2;
inline bool MetaCmd::has_join() const {
  return _has_bit(1);
}
inline void MetaCmd::clear_join() {
  if (join_ != NULL) join_->::ZPMeta::MetaCmd_Join::Clear();
  _clear_bit(1);
}
inline const ::ZPMeta::MetaCmd_Join& MetaCmd::join() const {
  return join_ != NULL ? *join_ : *default_instance_->join_;
}
inline ::ZPMeta::MetaCmd_Join* MetaCmd::mutable_join() {
  _set_bit(1);
  if (join_ == NULL) join_ = new ::ZPMeta::MetaCmd_Join;
  return join_;
}

// optional .ZPMeta.MetaCmd.Ping ping = 3;
inline bool MetaCmd::has_ping() const {
  return _has_bit(2);
}
inline void MetaCmd::clear_ping() {
  if (ping_ != NULL) ping_->::ZPMeta::MetaCmd_Ping::Clear();
  _clear_bit(2);
}
inline const ::ZPMeta::MetaCmd_Ping& MetaCmd::ping() const {
  return ping_ != NULL ? *ping_ : *default_instance_->ping_;
}
inline ::ZPMeta::MetaCmd_Ping* MetaCmd::mutable_ping() {
  _set_bit(2);
  if (ping_ == NULL) ping_ = new ::ZPMeta::MetaCmd_Ping;
  return ping_;
}

// optional .ZPMeta.MetaCmd.Update update = 4;
inline bool MetaCmd::has_update() const {
  return _has_bit(3);
}
inline void MetaCmd::clear_update() {
  if (update_ != NULL) update_->::ZPMeta::MetaCmd_Update::Clear();
  _clear_bit(3);
}
inline const ::ZPMeta::MetaCmd_Update& MetaCmd::update() const {
  return update_ != NULL ? *update_ : *default_instance_->update_;
}
inline ::ZPMeta::MetaCmd_Update* MetaCmd::mutable_update() {
  _set_bit(3);
  if (update_ == NULL) update_ = new ::ZPMeta::MetaCmd_Update;
  return update_;
}

// optional .ZPMeta.MetaCmd.Sync sync = 5;
inline bool MetaCmd::has_sync() const {
  return _has_bit(4);
}
inline void MetaCmd::clear_sync() {
  if (sync_ != NULL) sync_->::ZPMeta::MetaCmd_Sync::Clear();
  _clear_bit(4);
}
inline const ::ZPMeta::MetaCmd_Sync& MetaCmd::sync() const {
  return sync_ != NULL ? *sync_ : *default_instance_->sync_;
}
inline ::ZPMeta::MetaCmd_Sync* MetaCmd::mutable_sync() {
  _set_bit(4);
  if (sync_ == NULL) sync_ = new ::ZPMeta::MetaCmd_Sync;
  return sync_;
}

// -------------------------------------------------------------------

// MetaCmdResponse_Status

// required int32 code = 1;
inline bool MetaCmdResponse_Status::has_code() const {
  return _has_bit(0);
}
inline void MetaCmdResponse_Status::clear_code() {
  code_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 MetaCmdResponse_Status::code() const {
  return code_;
}
inline void MetaCmdResponse_Status::set_code(::google::protobuf::int32 value) {
  _set_bit(0);
  code_ = value;
}

// optional bytes msg = 2;
inline bool MetaCmdResponse_Status::has_msg() const {
  return _has_bit(1);
}
inline void MetaCmdResponse_Status::clear_msg() {
  if (msg_ != &_default_msg_) {
    msg_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& MetaCmdResponse_Status::msg() const {
  return *msg_;
}
inline void MetaCmdResponse_Status::set_msg(const ::std::string& value) {
  _set_bit(1);
  if (msg_ == &_default_msg_) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void MetaCmdResponse_Status::set_msg(const char* value) {
  _set_bit(1);
  if (msg_ == &_default_msg_) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void MetaCmdResponse_Status::set_msg(const void* value, size_t size) {
  _set_bit(1);
  if (msg_ == &_default_msg_) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MetaCmdResponse_Status::mutable_msg() {
  _set_bit(1);
  if (msg_ == &_default_msg_) {
    msg_ = new ::std::string;
  }
  return msg_;
}

// -------------------------------------------------------------------

// MetaCmdResponse

// required .ZPMeta.MetaCmdResponse.Type type = 1;
inline bool MetaCmdResponse::has_type() const {
  return _has_bit(0);
}
inline void MetaCmdResponse::clear_type() {
  type_ = 1;
  _clear_bit(0);
}
inline ::ZPMeta::MetaCmdResponse_Type MetaCmdResponse::type() const {
  return static_cast< ::ZPMeta::MetaCmdResponse_Type >(type_);
}
inline void MetaCmdResponse::set_type(::ZPMeta::MetaCmdResponse_Type value) {
  GOOGLE_DCHECK(::ZPMeta::MetaCmdResponse_Type_IsValid(value));
  _set_bit(0);
  type_ = value;
}

// required .ZPMeta.MetaCmdResponse.Status status = 2;
inline bool MetaCmdResponse::has_status() const {
  return _has_bit(1);
}
inline void MetaCmdResponse::clear_status() {
  if (status_ != NULL) status_->::ZPMeta::MetaCmdResponse_Status::Clear();
  _clear_bit(1);
}
inline const ::ZPMeta::MetaCmdResponse_Status& MetaCmdResponse::status() const {
  return status_ != NULL ? *status_ : *default_instance_->status_;
}
inline ::ZPMeta::MetaCmdResponse_Status* MetaCmdResponse::mutable_status() {
  _set_bit(1);
  if (status_ == NULL) status_ = new ::ZPMeta::MetaCmdResponse_Status;
  return status_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ZPMeta

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ZPMeta::MetaCmd_Type>() {
  return ::ZPMeta::MetaCmd_Type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ZPMeta::MetaCmdResponse_Type>() {
  return ::ZPMeta::MetaCmdResponse_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zp_5fmeta_2eproto__INCLUDED
